previews:
  generation: automatic

services:
  - type: web
    name: parental-control-backend
    runtime: docker
    repo: https://github.com/echska/ska
    branch: main
    rootDir: parental-control-system/backend
    plan: starter
    autoDeployTrigger: commit
    healthCheckPath: /health
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"

  - type: web
    name: parental-control-frontend
    runtime: static
    repo: https://github.com/echska/ska
    branch: main
    rootDir: parental-control-system/frontend
    buildCommand: npm install && npm run build
    staticPublishPath: parental-control-system/frontend/build
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: "18.20.4"
      - key: CI
        value: "false"
      - key: REACT_APP_API_BASE_URL
        value: https://parental-control-backend.onrender.com/api/v1
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
